// Configuration for 50 HTML lessons
const TOTAL_LESSONS = 50;

// Lesson answers for validation
const lessonAnswers = {
    1: "<!DOCTYPE html>",
    2: "<body></body>",
    3: "<title>My First Page</title>",
    4: "<h1>Welcome!</h1>",
    5: "<p>HTML is fun!</p>",
    6: "<br>",
    7: "<hr>",
    8: "<strong>Super Cool!</strong>",
    9: "<em>Amazing</em>",
    10: "<mark>Important</mark>",
    11: '<a href="https://example.com">Click Here</a>',
    12: '<a href="#" target="_blank">New Tab</a>',
    13: '<img src="cat.jpg" alt="A cute cat">',
    14: '<img src="dog.jpg" alt="Dog" width="150">',
    15: "<ul><li>Apples</li></ul>",
    16: "<ol><li>First Step</li></ol>",
    17: "<div>Hello Inside</div>",
    18: "<span>Highlight</span>",
    19: "<table><tr><td>Cell</td></tr></table>",
    20: "<table><tr><th>Name</th></tr></table>",
    21: "<form></form>",
    22: '<input type="text">',
    23: '<input type="password">',
    24: '<input type="email">',
    25: '<input type="number">',
    26: "<textarea></textarea>",
    27: "<button>Press</button>",
    28: '<input type="radio">',
    29: '<input type="checkbox">',
    30: "<select><option>Blue</option></select>",
    31: "<label>Email:</label>",
    32: "<fieldset></fieldset>",
    33: "<blockquote>Stay curious!</blockquote>",
    34: "<code>console.log()</code>",
    35: "<pre></pre>",
    36: '<abbr title="Cascading Style Sheets">CSS</abbr>',
    37: "<address>123 Main St</address>",
    38: '<audio controls></audio>',
    39: '<video controls></video>',
    40: '<iframe src="page.html"></iframe>',
    41: "<section></section>",
    42: "<article></article>",
    43: "<header></header>",
    44: "<footer></footer>",
    45: "<nav></nav>",
    46: "<main></main>",
    47: "<aside></aside>",
    48: "<figure></figure>",
    49: "<figcaption>My Photo</figcaption>",
    50: "<details><summary>Click Me</summary></details>"
};

// Lesson hints
const lessonHints = {
    1: "Copy it carefully! Start with &lt;! and end with &gt;",
    2: "Start with &lt;body&gt; and end with &lt;/body&gt;",
    3: "Use &lt;title&gt; and &lt;/title&gt; with the text in between",
    4: "Use &lt;h1&gt; to start and &lt;/h1&gt; to end",
    5: "Use &lt;p&gt; and &lt;/p&gt; tags",
    6: "Just type &lt;br&gt; - no closing tag needed!",
    7: "Just type &lt;hr&gt; - no closing tag needed!",
    8: "Use &lt;strong&gt; and &lt;/strong&gt; around the text",
    9: "Use &lt;em&gt; and &lt;/em&gt; around the text",
    10: "Use &lt;mark&gt; and &lt;/mark&gt; around the text",
    11: 'Use &lt;a href="URL"&gt;text&lt;/a&gt;',
    12: 'Add target="_blank" inside the opening tag',
    13: 'Use &lt;img src="..." alt="..."&gt; - no closing tag!',
    14: 'Add width="150" to your img tag',
    15: "Start with &lt;ul&gt;, add &lt;li&gt;Apples&lt;/li&gt;, end with &lt;/ul&gt;",
    16: "Use &lt;ol&gt; instead of &lt;ul&gt;",
    17: "Use &lt;div&gt; and &lt;/div&gt;",
    18: "Use &lt;span&gt; and &lt;/span&gt;",
    19: "Nest them: table &gt; tr &gt; td",
    20: "Use &lt;th&gt; for header cells",
    21: "Use &lt;form&gt; and &lt;/form&gt;",
    22: "No closing tag needed for input!",
    23: "Change the type to password",
    24: "Use type='email'",
    25: "Use type='number'",
    26: "Textarea DOES need a closing tag!",
    27: "Put text between &lt;button&gt; and &lt;/button&gt;",
    28: "Use type='radio'",
    29: "Use type='checkbox'",
    30: "Put &lt;option&gt; inside &lt;select&gt;",
    31: "Use &lt;label&gt; and &lt;/label&gt;",
    32: "Use &lt;fieldset&gt; and &lt;/fieldset&gt;",
    33: "Use &lt;blockquote&gt; and &lt;/blockquote&gt;",
    34: "Use &lt;code&gt; and &lt;/code&gt;",
    35: "Use &lt;pre&gt; and &lt;/pre&gt;",
    36: "Add title attribute with the full name",
    37: "Use &lt;address&gt; and &lt;/address&gt;",
    38: "Add the controls attribute",
    39: "Like audio but use video instead",
    40: 'Use &lt;iframe src="..."&gt;&lt;/iframe&gt;',
    41: "Use &lt;section&gt; and &lt;/section&gt;",
    42: "Use &lt;article&gt; and &lt;/article&gt;",
    43: "Use &lt;header&gt; and &lt;/header&gt;",
    44: "Use &lt;footer&gt; and &lt;/footer&gt;",
    45: "Use &lt;nav&gt; and &lt;/nav&gt;",
    46: "Use &lt;main&gt; and &lt;/main&gt;",
    47: "Use &lt;aside&gt; and &lt;/aside&gt;",
    48: "Use &lt;figure&gt; and &lt;/figure&gt;",
    49: "Use &lt;figcaption&gt; and &lt;/figcaption&gt;",
    50: "summary goes inside details"
};
